apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: ekscluster
  annotations:
    provider: aws
spec:
  crossplane:
    version: ">=v1.4.0-0"
  dependsOn:
    - provider: xpkg.upbound.io/crossplane-contrib/provider-aws
      version: ">=v0.18.2"
