apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: {{ include "eks.fullname" . }}-aws
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: {{ .Release.Namespace}}
      name: aws-credentials
      key: credentials
